name: Build .NET 8 App
permissions:
  contents: write
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: "latest"
        
      - name: Build Solution
        run: |
          dotnet --version
          dotnet build ./Installer/Installer.csproj --configuration Release --framework net8.0
      - name: Copy necessary files to release
        run: |
          mkdir Release
          copy ./Installer/bin/Release/net8.0-windows/* Release/
      - name: Publish Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: CrystalMarble
          path: Release
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: CrystalMarble
          path: Release
      - name: ZIPs the contents
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: "CrystalMarbleInstaller.zip"
          directory: Release
      - name: Create Relese
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "Release/*.zip"
          tag: "${{ github.ref_name }}"
          name: "CrystalMarbleInstaller-${{ github.ref_name }}"
