name: .NET Core Desktop
permissions:
  contents: write
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on:
      windows-latest # For a list of available runner types, refer to
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Installer.sln # Replace with your solution name, i.e. MyWpfApp.sln
      Project_Name: "Installer\\Installer.csproj"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Build
        run: msbuild $env:Project_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{matrix.configuration}}

      - name: Copy necessary files to release
        run: |
          mkdir Release
          copy ./Installer/bin/Release/net8.0-windows/* Release/
      - name: Publish Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: CrystalMarble
          path: Release
  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: CrystalMarble
          path: Release
      - name: ZIPs the contents
        uses: TheDoctor0/zip-release@0.7.1
        with:
          filename: "CrystalMarbleInstaller.zip"
          directory: Release
      - name: Create Relese
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "Release/*.zip"
          tag: "${{ github.ref_name }}"
          name: "CrystalMarbleInstaller-${{ github.ref_name }}"
